spring:
  freemarker:
    cache: false
    prefer-file-system-access: false
  datasource:
    url: jdbc:mysql://localhost/pybbs-springboot?useSSL=false&characterEncoding=utf8
    username: root
    password: 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
site:
  name: 新博社区
  intro: <h5>属于Java语言的bbs,也是属于新博的bbs</h5><p>在这里，您可以提问，回答，分享，诉说，这是个属于新博的社区，欢迎您的加入！</p>
  baseUrl: http://localhost:8080/
  staticUrl: http://localhost:8080/
  pageSize: 20
  uploadPath: /Users/tomoya/git/github/pybbs/target/classes/static/images/upload/
  sections:
    - 分享
    - 问答
    - 新闻
    - 博客
    - 招聘
  theme: bootstrap
  editor: markdown # 支持两种，1. markdown 2. wangeditor
  donate: false
  search: true